---
- name: Install operational packages
  ansible.builtin.package:
    name: [curl, jq, unzip, chrony]
    state: present
- name: Enable time synchronization
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: started
- name: Enforce SSH password authentication disabled
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart ssh
